create table contato (id int8 generated by default as identity, email varchar(255) not null, mensagem varchar(500) not null, primary key (id));
create table denuncias (id int8 generated by default as identity, email varchar(255) not null, nome varchar(255), ocorrido varchar(500) not null, telefone varchar(255) not null, primary key (id));
create table produtos_vendedor (id int8 generated by default as identity, nome_produto varchar(255) not null, preco float8 not null, primary key (id));
